import Head from "next/head";
import Navbar from "~/ui/Navbar";
import Image from "next/image";
import siteMapJPG from '../../public/siteMap.jpg'
import mentoring from '../../public/mentoring.png'
import liberalArtsWoman from '../../public/image.webp'

//This page is primarily a digital brochure explaining the usefulness of the application

export default function Home() {
    //No functions needed becasue Login is through Navbar

  return (
    <>
      <Head>
        <title>Origin Point Career Strategy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex flex-col items-center justify-center">
        <Image className='w-full max-w-4xl' src={mentoring} alt="Site Map" />
        <div className="text-center space-y-6 pb-10">
            <h1 className="text-3xl md:text-5xl lg:text-6xl font-bold font-sans">Helping you navigate your future</h1>
            <h3>Guidance for Liberal Arts Students seeking employment</h3>
        </div>
        <hr className="h-0.5 bg-black w-5/6 mx-auto"/>
        <div className="container flex flex-col justify-center items-center gap-6 px-4 py-8 ">
            <Image className='w-full max-w-4xl' src={liberalArtsWoman} alt="Liberal arts woman tyring to get money that is being dangled in front of her" />
            <h2 className='text-2xl font-bold font-sans'>A Case for Mentorship</h2>
            <h3 className='max-w-4xl'>Increasingly there has been a push towards professionalization at universities across the
                 United States. This means students roughly are going into one of three broad based major 
                 groups which are healthcare, business, and engineering.
            </h3>
            <h3 className='max-w-4xl'>To access these jobs though Liberal Arts majors, need some rudimentary business training and 
                people willing to give them a chance. As is often stated it is not what you know but you know.

            </h3>
            <h3 className="max-w-4xl">
                A mentor is a crucial first step in getting one's foot in the door and our product aims to address that issue.
            </h3>
        </div>
        <hr className="h-0.5 bg-black w-5/6 mx-auto"/>
        <div className="container flex flex-col justify-center items-center gap-6 px-4 py-8">
            <h3 className='text-2xl font-bold font-sans'>Technical Layout</h3>
            <Image className='w-full max-w-4xl' src={siteMapJPG} alt="Site Map" />
            <h3 className='max-w-4xl'>We have developed an online database of mentors for students to access.
                The mentors have a short blurb about themselves and align themselves by industry and role 
                making it easier for students to connect with a mentor that will facilitate their goals and
                 push them along in their careers.
            </h3>
            <h3 className='max-w-4xl'>
                The tech stack we chose implement this was Next.js hosted with Vercel/AWS. The database
                 ORM (Object Relational Manager) was Prisma and hosted on Planetscale.
                We believe are simple product is huge first step in keeping the diversity and intellectual 
                freedom university is supposed to be about. If we lose the diverse major pool that is intrinsic 
                to the university innovation and society will suffer.
            </h3>
        </div>
        <hr className="h-0.5 bg-black w-5/6 mx-auto"/>
      </main>
    </>
  );
}
