import Head from "next/head";
import Link from "next/link";
import { SignInButton, SignOutButton,SignIn,UserButton, useUser} from "@clerk/nextjs";
import Navbar from "~/ui/Navbar";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
            <UserButton />
        </div>
      </main>
    </>
  );
}
